const types = {
  AUTHENTICATE: 'AUTH/AUTHENTICATE',
  RESET: 'AUTH/RESET',

  SIGNUP: 'AUTH/SIGNUP',
  VERIFY_JWT: 'AUTH/VERIFY_JWT',
  CURRENT_USER: 'AUTH/CURRENT_USER',
  USER_GET: 'AUTH/USER_GET',
  LOGOUT: 'AUTH/LOGOUT'
}

export default types;